# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

# File path: .github/workflows/main_azurepiratefaps.yml

name: azurepiratefaps

on:
  push:
    branches:
      - main
    paths:
      - PS/**
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './PS' # set this to the path to your web app project, defaults to the repository root

defaults:
  run:
    working-directory: './PS'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'azurepiratefaps'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1708642192A64ABD845A8203F40202B5 }}

  restart-app:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_PIRATE_SPN_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        # azcliversion: 2.30.0
        inlineScript: |
          az functionapp restart --name "azurepiratefaps" --resource-group "AzurePirate"