name: apis-azpirate

on:
  push:
    branches:
      - main
      - dev
    paths:
      - apis-azpirate/**
      - .github/workflows/apis-azpirate.yml
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './apis-azpirate'

defaults:
  run:
    working-directory: './apis-azpirate'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: api-azpirate
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.APISFA_PUBLISH_PROFILE }}